source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'mysql2', '~>0.2.7'
gem 'mail'
gem 'devise'
gem 'nested_form'
gem 'haml-rails'
gem 'compass', '>= 0.11.1'

gem 'paperclip', '~>2.3'
gem 'will_paginate', '3.0.pre2'
gem 'jquery-rails', '>= 1.0.12'
gem 'liquid'
gem 'capistrano'
gem 'active_utils'
gem 'acts-as-taggable-on', '~>2.1.0'
gem 'friendly_id', '~> 4.0.0.beta14'
gem 'activemerchant', :require => 'active_merchant'

gem 'ruby-debug-base19', '0.11.26'
gem 'linecache19', '0.5.13'
gem 'ruby-debug19', :require=>'ruby-debug'